version: '3.1'
services:
    web:
        image: 'nginx:alpine'
        restart: always
        working_dir: /var/www/html
        volumes:
            - '.:/var/www/html'
            - './docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '8000:80'
        depends_on:
            - database
            - redis
        networks:
            - app-network

    app:
        build: docker/php
        restart: always
        working_dir: /var/www/html
        volumes:
            - '.:/var/www/html'
            - './docker/php/php-ini-overrides.ini:/etc/php/8.0/fpm/conf.d/99-overrides.ini'
        networks:
            - app-network

    database:
        image: 'mysql:5.7'
        restart: always
        working_dir: /var/www/html
        volumes:
            - '.:/var/www/html'
            - ./docker/data/mysql:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=larafood
            - MYSQL_USER=larafood
            - MYSQL_PASSWORD=larafood
        ports:
            - '9002:3306'
        networks:
            - app-network

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
            - 8080:80
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=database
            - PMA_USER=root
            - PMA_PASSWORD=root
        links:
            - database
        depends_on:
            - database
        networks:
            - app-network

    redis:
        image: redis
        restart: always
        ports:
            - "6379:6379"
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

